[package]
name = "aegis-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
tokio = { workspace = true }
serde.workspace = true
serde_json.workspace = true
serde_yaml = "0.9"
uuid = { workspace = true }
chrono = { workspace = true }
humantime-serde = "1.1"
thiserror = { workspace = true }
anyhow = { workspace = true }
handlebars = "5.1"
async-trait = "0.1"
futures = { workspace = true }
bollard.workspace = true
sqlx = { workspace = true, features = ["runtime-tokio-native-tls", "postgres", "uuid", "chrono", "json"] }
tracing.workspace = true
axum.workspace = true
tokio-stream = "0.1.18"
tower-http.workspace = true
hostname = "0.4"
dirs = "5.0"
reqwest = { version = "0.12", features = ["json"] }
